package org.example.topdown;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import java.util.List;

/**
 * This class was generated by the XML-WS Tools. XML-WS Tools 4.0.1 Generated source version: 3.0
 */
@WebService(name = "CarService", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({ObjectFactory.class})
public interface CarService {

  /**
   * @param arg0
   * @throws CarExistsEx_Exception
   */
  @WebMethod
  @RequestWrapper(
      localName = "addCar",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.AddCar")
  @ResponseWrapper(
      localName = "addCarResponse",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.AddCarResponse")
  public void addCar(@WebParam(name = "arg0", targetNamespace = "") Car arg0)
      throws CarExistsEx_Exception;

  /**
   * @param arg0
   * @throws CarNotFoundEx_Exception
   */
  @WebMethod
  @RequestWrapper(
      localName = "removeCar",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.RemoveCar")
  @ResponseWrapper(
      localName = "removeCarResponse",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.RemoveCarResponse")
  public void removeCar(@WebParam(name = "arg0", targetNamespace = "") int arg0)
      throws CarNotFoundEx_Exception;

  /**
   * @param arg0
   * @return returns org.example.topdown.Car
   * @throws CarNotFoundEx_Exception
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
      localName = "getCar",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.GetCar")
  @ResponseWrapper(
      localName = "getCarResponse",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.GetCarResponse")
  public Car getCar(@WebParam(name = "arg0", targetNamespace = "") int arg0)
      throws CarNotFoundEx_Exception;

  /**
   * @return returns java.util.List<org.example.topdown.Car>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
      localName = "getAllCars",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.GetAllCars")
  @ResponseWrapper(
      localName = "getAllCarsResponse",
      targetNamespace = "http://service.example.org/",
      className = "org.example.topdown.GetAllCarsResponse")
  public List<Car> getAllCars();
}
