package org.example.topdownv3;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by the XML-WS Tools. XML-WS Tools 4.0.1 Generated source version: 3.0
 */
@WebFault(name = "CarExistsEx", targetNamespace = "http://service.example.org/")
public class CarExistsEx_Exception extends Exception {

  /** Java type that goes as soapenv:Fault detail element. */
  private CarExistsEx faultInfo;

  /**
   * @param faultInfo
   * @param message
   */
  public CarExistsEx_Exception(String message, CarExistsEx faultInfo) {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   * @param cause
   * @param faultInfo
   * @param message
   */
  public CarExistsEx_Exception(String message, CarExistsEx faultInfo, Throwable cause) {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  public CarExistsEx_Exception() {
    super("This car already exists!");
  }

  /**
   * @return returns fault bean: org.example.topdownv3.CarExistsEx
   */
  public CarExistsEx getFaultInfo() {
    return faultInfo;
  }
}
